### PR TITLE
fix month in log_message

### PR DESCRIPTION
**Pull request by edquist**
localtime's month field is zero-indexed (0..11)

### CODE REVIEW

**Comment by osg-cat** [comment]
Let’s fix this properly (i.e., using strftime or the like). I don’t care who does it, but the JIRA ticket is currently assigned to Mat.

For the record, I don’t want to see us writing date/time formatting code ourselves. Always use standard libraries for that.

**Comment by edquist** [comment]
Re-opened PR with `strftime` to do the formatting.

**Comment by osg-cat** [comment]
Much better approach. But it’s been a long time since I looked at Perl carefully… @matyasselmeci would you like to do the honors?

**Comment by matyasselmeci** [comment]
Looks fine to me.

**Pull request merged**
